### ISSUE TITLE
Add support for running with x11docker?

### ISSUE THREAD

**Issue by sxiii** [jlesage/docker-baseimage-gui#27]
Hi! I've tried to run your example, replacing xterm with glxspeheres64 (the installed correctly from edge/testing repo of alpine) via x11docker.

Tested with a lot of different options but I got all the time this error:
```
/bin/sh: -c requires an argument
```
Do you have any idea why is this? Thanks.

**Comment by jlesage** [comment]
When exactly this error is showing up?  Also, what is the content of your `startapp.sh`?

**Comment by oakla** [comment]
Hey sxiii (and any one else who has this error message)

I got the same error message. It turned out the cause was that I forgot to give arguments to RUN command in my dockerfile.

I have no idea what it is that you're doing, but seeing as there are no other answers here, I thought it wouldn't hurt for me to chime in.

**Comment by sxiii** [comment]
Oh cool. I'll close this than thanks @oakla
